sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFTKu6xmWUbXmJyPpuW
    access-key-secret: dIduVf2do2KV6gShXwXN953F6KY6rG
    bucket-name: sky-take-out-youngyc
  redis:
    host: localhost
    port: 6379
#    password: requirepass
#    database: 0
  wechat:
    appid: wx2baf8d741c19e913
    secret: 595cc928d3c009447be3332cfb606cfd